### ISSUE TITLE
Error module magicgui not found 

### ISSUE THREAD

**Issue by romainGuiet** [computational-cell-analytics/micro-sam#128]
Dear micro-sam team,

I created a new env and tried to install micro_sam

```
>mamba create -n microsam python=3.9 micro_sam -y 
>...
>mamba activate microsam 
>micro_sam.annotator
Traceback (most recent call last):
  File "D:\conda\conda-envs\microsam\Scripts\micro_sam.annotator-script.py", line 5, in <module>
    from micro_sam.sam_annotator.annotator import main
  File "D:\conda\conda-envs\microsam\lib\site-packages\micro_sam\sam_annotator\__init__.py", line 1, in <module>
    from .annotator import annotator
  File "D:\conda\conda-envs\microsam\lib\site-packages\micro_sam\sam_annotator\annotator.py", line 2, in <module>
    import magicgui
ModuleNotFoundError: No module named 'magicgui'

```

I then tried to install napari (because I knew magicgui is a dependency)

```
>mamba install napari / or 'napari[all]'
...
>micro_sam.annotator
Traceback (most recent call last):
  File "D:\conda\conda-envs\microsam\Scripts\micro_sam.annotator-script.py", line 5, in <module>
    from micro_sam.sam_annotator.annotator import main
  File "D:\conda\conda-envs\microsam\lib\site-packages\micro_sam\sam_annotator\__init__.py", line 1, in <module>
    from .annotator import annotator
  File "D:\conda\conda-envs\microsam\lib\site-packages\micro_sam\sam_annotator\annotator.py", line 6, in <module>
    from PyQt5.QtWidgets import QFileDialog, QMessageBox
ModuleNotFoundError: No module named 'PyQt5'
```

finally running 
```
>pip install PyQt5, 
...
>micro_sam.annotator
```
I got the GUI 🎉 : 

![image](https://github.com/computational-cell-analytics/micro-sam/assets/8309560/62672383-5d68-4adf-b111-689845670c1d)

Best regards,

Romain

**Comment by constantinpape** [comment]
Thanks for the report @romainGuiet ! This is expected, but we should explain it better in the installation instructions.
I will update these soon (together with another big update that will come end of this week or beginning of next ;) ) and then close the issue.

**Comment by constantinpape** [comment]
I have updated the installation instructions accordingly: https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#from-conda
