### ISSUE TITLE
annotator_2d dtype support

### ISSUE THREAD

**Issue by jeskowagner** [computational-cell-analytics/micro-sam#14]
Hi,

Thanks for making this available, I'm very keen to try it out! My images tend to be `uint16` which currently seems to not play nice with `annotator_2d.py`. Probably would need some transformation in `_compute_2d` to fix that?
It's the same with `float32`, `float64`, `int64`, `uint64`, `uint32`, and `int32`. So I am not sure which dtype would be the correct one and would appreciate some pointers. Thanks!

<details>
  <summary>Traceback</summary>

```python
Traceback (most recent call last):
  File ".../bin/micro_sam.annotator_2d", line 33, in <module>
    sys.exit(load_entry_point('micro-sam', 'console_scripts', 'micro_sam.annotator_2d')())
  File ".../micro-sam/micro_sam/sam_annotator/annotator_2d.py", line 184, in main
    annotator_2d(
  File ".../micro-sam/micro_sam/sam_annotator/annotator_2d.py", line 44, in annotator_2d
    IMAGE_EMBEDDINGS = util.precompute_image_embeddings(PREDICTOR, raw, save_path=embedding_path, ndim=2)
  File ".../micro-sam/micro_sam/util.py", line 236, in precompute_image_embeddings
    image_embeddings = _compute_2d(input_, predictor) if save_path is None else\
  File ".../micro-sam/micro_sam/util.py", line 119, in _compute_2d
    predictor.set_image(image)
  File ".../lib/python3.10/site-packages/segment_anything/predictor.py", line 56, in set_image
    input_image = self.transform.apply_image(image)
  File ".../lib/python3.10/site-packages/segment_anything/utils/transforms.py", line 31, in apply_image
    return np.array(resize(to_pil_image(image), target_size))
  File ".../lib/python3.10/site-packages/torchvision/transforms/functional.py", line 335, in to_pil_image
    raise TypeError(f"Input type {npimg.dtype} is not supported")
TypeError: Input type uint16 is not supported
```

<details>

**Comment by constantinpape** [comment]
Thanks for pointing this out!
SAM expects 8bit (uint8) images. I updated the functionality in #15 so that other dtypes are supporting (by casting the input images to uint8).
Hope this fixes your issue!

**Comment by jeskowagner** [comment]
That was by far the fastest time to fix, PR and merge that I have ever seen after filing an issue. Thank you, works perfectly now!

**Comment by constantinpape** [comment]
> That was by far the fastest time to fix, PR and merge that I have ever seen after filing an issue.

This was an easy one that was on my list anyway ;).

Let us know if you run into any issues, or if you have any tips on how to improve the user experience; we are just getting started with this :).
