### ISSUE TITLE
dev branch : " importError: cannot import name 'UNETR' from 'torch_em.model' "

### ISSUE THREAD

**Issue by Nal44** [computational-cell-analytics/micro-sam#385]
(C:\Users\m197816\AppData\Local\micro_sam) C:\Users\m197816\micro-sam>micro_sam.annotator
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\m197816\AppData\Local\micro_sam\Scripts\micro_sam.annotator.exe\__main__.py", line 4, in <module>
  File "C:\Users\m197816\AppData\Local\micro_sam\Lib\site-packages\micro_sam\sam_annotator\__init__.py", line 5, in <module>
    from .annotator import annotator
  File "C:\Users\m197816\AppData\Local\micro_sam\Lib\site-packages\micro_sam\sam_annotator\annotator.py", line 13, in <module>
    from .annotator_2d import annotator_2d
  File "C:\Users\m197816\AppData\Local\micro_sam\Lib\site-packages\micro_sam\sam_annotator\annotator_2d.py", line 11, in <module>
    from .. import instance_segmentation, util
  File "C:\Users\m197816\AppData\Local\micro_sam\Lib\site-packages\micro_sam\instance_segmentation.py", line 26, in <module>
    from torch_em.model import UNETR
ImportError: cannot import name 'UNETR' from 'torch_em.model' (C:\Users\m197816\AppData\Local\micro_sam\Lib\site-packages\torch_em\model\__init__.py)

**Comment by anwai98** [comment]
Hi @Nal44, can you run the following script in your terminal within your environment and share with us the output:
`python -c "import torch_em; print(torch_em.__version__)`

My suspicion is: you have an older version of `torch-em` installed.

**Comment by Nal44** [comment]
Hi ,
Thanks
Output : 0.5.2

did pip --upgrade torch-em : no changes

But conda worked : 
conda install -c conda-forge torch_em 
0.6.1 now

it works now :)

thanks
antho

**Comment by anwai98** [comment]
Awesome!
