### ISSUE TITLE
Reopening: What data format is used for micro_sam.annotator_tracking?

### ISSUE THREAD

**Issue by ludalin-ucla** [computational-cell-analytics/micro-sam#49]
Previous discussion: https://github.com/computational-cell-analytics/micro-sam/issues/45
> Hi @ludalin-ucla, in this case you need to specify the pattern to load the files in the folder vie the `-k` parameter. If you want to load all files with the ending `.tif` you can do it like this:
> 
> ```
> micro_sam.annotator_tracking -i path/to/folder/with/images  -k *.tif
> ```
> 
> (and if the files end with `.tiff` you would use `*.tiff` etc.)
> 
> > An example of tiff stacks is attached.
> 
> Unfortunately attachements via mail don't work, so I couldn't test this on your data. But I am pretty sure using the `-k` argument should fix your problem. Feel free to reopen if you're still having an issue with this.

Hi, I tried to add the parameter as you mentioned, and another error comes:
micro_sam.annotator_tracking: error: unrecognized arguments: 0002.tif 0003.tif 0004.tif 0005.tif 0006.tif
(the first image in the folder is 0001.tif).

**Comment by constantinpape** [comment]
Ok. Can you then please upload the example data and the exact command that produces the error, so that I can see whether I can reproduce it? Thanks!

**Comment by ludalin-ucla** [comment]
[test_tiff.zip](https://github.com/computational-cell-analytics/micro-sam/files/11806031/test_tiff.zip)
Here it is. Here I use iMac OSX. After extract the folder to the desktop,
user$ conda activate micro-sam
user$ cd desktop 
user$ cd test_tiff
user$ micro_sam.annotator_tracking -i "./" -k *.tif

Besides, if I do not change the working directory and put the full directory of the folder after -i as below:
user$ micro_sam.annotator_tracking -i "/desktop/test_tiff" -k *.tif,

The error as below will come:
Traceback (most recent call last):
  File "/Users/user/anaconda3/envs/napari-env/bin/micro_sam.annotator_tracking", line 33, in <module>
    sys.exit(load_entry_point('micro-sam', 'console_scripts', 'micro_sam.annotator_tracking')())
  File "/Users/user/Desktop/micro-sam/micro_sam/sam_annotator/annotator_tracking.py", line 516, in main
    raw = util.load_image_data(args.input, ndim=3, key=args.key)
  File "/Users/user/Desktop/micro-sam/micro_sam/util.py", line 323, in load_image_data
    image_data = f[key]
  File "/Users/user/anaconda3/envs/napari-env/lib/python3.10/site-packages/elf/io/image_stack_wrapper.py", line 37, in __getitem__
    raise ValueError(f"Invalid file pattern {pattern}")
ValueError: Invalid file pattern /desktop/test_tiff/*.tif

Furthermore, if I change the working directory to the desktop (cd desktop) and put the incomplete directory of the folder after -i as below:
user$ micro_sam.annotator_tracking -i "/test_tiff" -k *.tif,
or user$ micro_sam.annotator_tracking -i "./test_tiff" -k *.tif,
It will try to extract all images of the working directory, aka the desktop folder, rather than just images inside the target folder.

**Comment by constantinpape** [comment]
The following works for me after extracting your zip file:
```
$ micro_sam.annotator_tracking -i test_tiff/test_tiff -k *.tif  --model_type vit_b
```
( `--model_type vit_b` uses a smaller model so that computing the embeddings is faster, you don't really need it)

And it opens the tracking annotator with all 6 images:

https://github.com/computational-cell-analytics/micro-sam/assets/4263537/4df2dd60-d911-41e7-b0fa-d0b9df01ad0c

One thing I can think of: maybe you're not using the latest version. Can you try to pull from the master branch again and see if this fixes the issue?

**Comment by constantinpape** [comment]
> ValueError: Invalid file pattern /desktop/test_tiff/*.tif

I also checked this error. It means that the filepath is not valid because no files that match the pattern can be found. 
You can check if the path is valid by running the following small script in python:
```python
from glob import glob
files = glob(pattern)   # e.g. pattern = "/desktop/test_tiff/*.tif"
print(len(files))
```
If this prints zero then the way you specifiy the filepath is wrong (it should print the number of images in the folder).

**Comment by ludalin-ucla** [comment]
I find that if I use the complete directory it works, but not the partial ones after cd to a specific folder.

**Comment by constantinpape** [comment]
> I just right clicked and got the full directory of the folder like "/Users/user/Desktop/test_tiff/" and it worked.

Ok, so I think the issue you had before was then just with a wrong filepath. If you use absolute paths in the future it should work.
I think it's resolved and will close this issue, feel free to open another one if something else comes up.
